doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4
        options:
            # PDO::MYSQL_ATTR_INIT_COMMAND
            1002: "SET time_zone = '+00:00'"
        profiling_collect_backtrace: '%kernel.debug%'

when@test:
    doctrine:
        dbal:
            url: '%env(resolve:TEST_DATABASE_URL)%'
