# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session:
        handler_id: app.session.handler
        name: StreamNotifyBot
        cookie_lifetime: 0
        cookie_path: /
        cookie_secure: auto
        cookie_httponly: true
        cookie_samesite: strict
        gc_maxlifetime: 1800
        gc_probability: 1
        gc_divisor: 100

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file

when@prod:
    framework:
        session:
            name: __Host-StreamNotifyBot
            cookie_secure: true
